### PR TITLE
Added README

### PR DESCRIPTION
**Pull request by aa2006**

### CODE REVIEW

**Review by DamieFC — APPROVED** [review]
YAY

**Comment by DamieFC** [comment]
> YAY

Rather, YAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAY

**Comment by timas130** [comment]
Pull request approval speedrun Any% world record

**Comment by notbluu** [comment]
I would add a link to the LICENSE.md (if that gets added tho lol)

**Comment by DamieFC** [comment]
@notbluu That's coming tomorrow

**Pull request merged**
