### PR TITLE
README: Made it clear that you need to clone recursively

### PR DESCRIPTION
**Pull request by unsafecast**
We had two issues in the past with people not realizing they need to clone recursively since submodules, so I though it would be a good idea to do that :^)

### CODE REVIEW

**Review by DamieFC — APPROVED** [review]
Good idea

**Review by AviadBag — COMMENTED** [review]
Maybe it's a good idea to even include the command to clone recureively, like that:
`git clone --recursive https://github.com/MandelbrotOS/MandelbrotOS.git`

**Comment by AnantTiwari-Naman** [comment]
And maybe add a command for updating submodules if they already cloned the repo?

**Comment by unsafecast** [comment]
@AviadBag added the command, and @AnantTiwari-Naman I added that too \:)

**Pull request closed without merging**
