### PR TITLE
Rewrite shell

### PR DESCRIPTION
**Pull request by timas130**
I fixed some `-Wextra` warnings and rewrote `kshell.c`, so adding commands is now easier and the shell is overall just better.

### CODE REVIEW

**Comment by CaydendW** [comment]
Your kernel is very behind. Please update your files before I merge. Thank you.

**Comment by timas130** [comment]
> Your kernel is very behind. Please update your files before I merge. Thank you.

I regularly pull from master, but I'll check when I get home. Maybe it's behind `ATA_2`?

**Comment by timas130** [comment]
I checked it on my phone and the only commit that's missing from master is 98a851d258293bc5fe1abe73c8d924a5c1f426d3 and it's resolved in my branch.

**Comment by CaydendW** [comment]
Checked it out. It's good. Merging

**Pull request merged**
