### PR TITLE
Fixed the build scripts, made the dependencies as submodules

### PR DESCRIPTION
**Pull request by unsafecast**
Along with those changes I added to more required packages that were missing in the repo & I also made the makefile a little bit more intuitive

### CODE REVIEW

**Comment by unsafecast** [comment]
Also, when running the scripts, **make sure it's from the root of the repo**. Don't `cd` into `/scripts`

**Comment by segfaultdev** [comment]
Ooooooooh nice (:.

**Review by A52-bit — APPROVED** [review]
Everything seems ok

**Comment by Chai112** [comment]
does this mean my installation will work? lol :)

**Comment by unsafecast** [comment]
@Chai112 depends on what your error is

**Review by segfaultdev — APPROVED** [review]
Nice!

**Comment by Chai112** [comment]
do you want me to try reinstall? It would probably take overnight and I'll report any stuff in issues

**Comment by unsafecast** [comment]
@Chai112 sure, why not.

**Comment by AtieP** [comment]
Don't merge yet please I am working on LAI support and this will totally break it, what about after i finish it and gets merged you patch it too and then merge this one

**Review by AtieP — COMMENTED** [review]
Don't merge yet please I am working on LAI support and this will totally break it, what about after i finish it and gets merged you patch it too and then merge this one

**Comment by A52-bit** [comment]
@AtieP The fixes doesn't seem to break the LAI support, I think it's OK

**Comment by unsafecast** [comment]
I took a look too and the only files that we both changed are the Makefile and .gitignore.

And it looks like there aren't any conflicts

**Comment by CaydendW** [comment]
I will merge this once @AtieP gives me a green light. This should not be too long and I'll merge it.

**Pull request merged**
